In [109]:
import numpy as np
from scipy.linalg import cholesky, solve_triangular, cho_solve, cho_factor
from scipy.linalg import solve
from scipy.optimize import minimize

In [110]:
A = np.array([
    [26, 10, 2, 1],
    [1, 14, -5, 1],
    [2, -5, 0, 0],
    [1, 1, 0, 0]])

b = np.array([-1,-1,2,1]).reshape(-1,1)

sol = solve(A, b)

In [111]:
sol

array([[  1.        ],
       [  0.        ],
       [ -3.57142857],
       [-19.85714286]])

In [112]:
def f(x,y):
    return 26*x**2+10*x*y+7*y**2+x+y+2

In [113]:

f(*sol[:2])

array([29.])

Using scipy.optimize

In [114]:
def f(x):
    return 26*x[0]**2+10*x[0]*x[1]+7*x[1]**2+x[0]+x[1]+2

In [115]:
cons = ({'type': 'eq',
         'fun' : lambda x: np.array([2*x[0] - 5*x[1] - 2, x[0] + x[1] - 1])})

In [130]:
x0 = np.array([3, 2])

res = minimize(f, x0,constraints=cons)


In [131]:
res.fun

29.00000000000002

In [132]:
res.x

array([1., 0.])